### ISSUE TITLE
Broken Homepage Styling

### ISSUE THREAD

**Issue by neocybereth** [decentraland/old-documentation#105]
I know this has nothing to do with the docs, but I couldn't find a proper place to put this issue. The UI on the main page of Decentraland.org breaks on resizing.

![screen shot 2018-10-12 at 9 31 46 am](https://user-images.githubusercontent.com/14209806/46832234-042b4080-ce02-11e8-91fa-c0d0414a2407.jpg)

**Comment by nearnshaw** [comment]
Thanks for the feedback!
We're actually right in the middle of a full redesign of our main landing page, so that issue will surely be fixed then. 
I passed your comments on to our web developers.
I'll mark this issue as closed, but we'll be mindful of it for our redesign.
Thanks!

**Comment by neocybereth** [comment]
cool thanks. Could you pass on my other issue to the dev team too please? Shown here: https://github.com/decentraland/marketplace/issues/565

**Comment by nearnshaw** [comment]
Thanks, I'll point this issue out to them too!
Cheers!
