### ISSUE TITLE
Link to inaccurate information

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/old-documentation#300]
The documentation on page https://github.com/decentraland/documentation/blob/master/_posts/development-guide/2018-02-6-shape-components.md links to https://github.com/decentraland/ecs-reference , an outdated (or inaccurate) documentation that don't have **Issues** tab enabled.

> An example of inaccurate information is the page https://github.com/decentraland/ecs-reference/blob/master/docs-latest/decentraland-ecs.textshape.md where many properties don't have any effect.

Maybe the information on `decentraland/ecs-reference` should be rebuilt?

**Comment by nearnshaw** [comment]
I agree, we should generate something new that includes this info

In the meantime, I removed this outdated link in this PR, thanks!
https://github.com/decentraland/documentation/pull/556
