### ISSUE TITLE
alpha is listed as a Material property

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/old-documentation#309]
**alpha** is listed as a **Material** property here: https://github.com/decentraland/ecs-reference/blob/master/docs-latest/decentraland-ecs.material.md

but it is not: https://github.com/decentraland/explorer/blob/9c0b0c0baf8de74d14f2cb57f6046c557f7dc059/unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs#L15

**Comment by nearnshaw** [comment]
The linked reference is super outdated :/
I'm closing this issue, as it's not relevant to the documentation site. The docs on Materials fortunately don't list that non-existing property
