### ISSUE TITLE
FAQ candidate: "Where is everyone?"

### ISSUE THREAD

**Issue by justin-hackin** [decentraland/old-documentation#375]
I was curious about this project so I take a look and was really impressed but I couldn't help but wonder "Where is everyone?!"  I noticed the "Friends" section but I don't know anyone using the platform.  I thought to myself "maybe I can only see people who are my friends" and then "...but how do I make friends?".  I found the events section and wondered whether or not everyone attending an event could see each other or not.

So, has this place just been a ghost town or am I missing something?  I tried looking for people on the map too.

For any prospective investor in decentraland, it appears obvious that the value of one's investment depends upon the "network effect" so I think making all this clearer could be a great boon to your platform.  Hope to be interacting soon.

**Comment by nearnshaw** [comment]
Closing as this is not an issue with the content of the Documentation site
