### ISSUE TITLE
Suggested improvements to the Smart Items documentation

### ISSUE THREAD

**Issue by cfravel** [decentraland/old-documentation#449]
https://docs.decentraland.org/development-guide/smart-items/

1. There is a misworded sentence, 
It currently reads:
"When new players join the scene, the make sure that they obtain any relevant information from other players about the current state of the item. To do this, the door item sends out a channel.request when spawning, and if there are any other players with instances of that door they will reply with a boolean indicating if the door is currently open."

It should probably read:
"When new players join the scene, make sure that they obtain any relevant information from other players about the current state of the item. For example, to do this, the door item should out a channel.request when spawning, and if there are any other players with instances of that door there should be code that will reply with a boolean indicating if the door is currently open."

2. The general item data listed for the manifest has the keywords capitalized, like "Name", should be lowercase, like "name".

3. The manifest documentation fails to mention what to do with the initial id field.  I assume one should give it a unique UUID, which can be obtained from an online UUID V4 generator.

**Comment by nearnshaw** [comment]
Thanks Carl, I just wrote a PR with the changes you proposed!

https://github.com/decentraland/documentation/pull/558
