### ISSUE TITLE
Showcase Bitvavo in the MANA wallet docs

### ISSUE THREAD

**Issue by noahpierau** [decentraland/old-documentation#483]
Dear MANA team,

We are contacting you on behalf of Bitvavo, one of the biggest regulated EUR exchanges in Europe. We are proudly based in Amsterdam and have been offering the MANA/EUR trading pair to our customers for some time now. According to data from CoinMarketCap we currently provide a top 3 MANA market worldwide based on EUR volume.

In your docs we saw the page https://docs.decentraland.org/examples/get-a-wallet/ where you showcase 3 exchange options for MANA. We were wondering: can you add Bitvavo to this list? We created a custom asset page https://bitvavo.com/en/decentraland that you could link to (for localized versions, just replace "en" with "de", "es", "fr", "it" or "nl" in the link).

Thank you for considering the opportunity to add Bitvavo to the list of exchanges.

Kindly let us know if you have any questions.

**Comment by nearnshaw** [comment]
Closing, as this is not a documentation issue
